### ISSUE TITLE
Cannot build with msbuild - Parameter "AssemblyFiles" has invalid value "/usr/lib/mono/4.7.2-api/mscorlib.dll".

### ISSUE THREAD

**Issue by rzarai** [arp242/RimWorld-RainingBlood#1]
Hey man. Stumbled upon this error upon build:

`/usr/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): error MSB3248: Parameter "AssemblyFiles" has invalid value "/usr/lib/mono/4.7.2-api/mscorlib.dll". Could not load file or assembly 'System.Reflection.Metadata, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
`
  
For some reason it gives me invalid value **"/usr/lib/mono/4.7.2-api/mscorlib.dll"** for parameter **"AssemblyFiles"**.  
I checked - it is not an error of missing library, because this file exists in said directory along with multiple others.  
Have you ever encountered this error? And if so, what did you did to resolve this?  
Googleing about the issue so far yielded no result.  
  
If it matters I'm on manjaro linux. I can give any additional info if necessary.

**Comment by rzarai** [comment]
Solved it.  
  
The solution:
```
mkdir -p /tmp/mono-deb
cd /tmp/mono-deb
FILE=$(curl --silent https://download.mono-project.com/repo/ubuntu/dists/preview-focal/main/binary-amd64/Packages | grep -Po "(?<=Filename: ).+mono-roslyn.+\\.deb")
curl https://download.mono-project.com/repo/ubuntu/${FILE} > mono.deb
ar p mono.deb data.tar.xz | tar xJf -  ./usr/lib/mono/4.5/System.Reflection.Metadata.dll --strip-components 5
sudo mv /usr/lib/mono/4.5/System.Reflection.Metadata.dll /usr/lib/mono/4.5/System.Reflection.Metadata.dll_OLD
sudo cp System.Reflection.Metadata.dll /usr/lib/mono/4.5
```
The problem was the manjaro linux. Looks like msbuild is a bit broken on this system.

Script from: https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-Arch#arch-user-repository

**Comment by rzarai** [comment]
Thank you for the tutorial btw.

**Comment by arp242** [comment]
Did you install the .NET from the blog post: https://www.arp242.net/rimworld-mod-linux.html#decompiling-the-code? I think that's roughly the same?

I'm not very familiar with the C#/.NET ecosystem at all, so I'm not really sure why you need to do this 🤔

**Comment by rzarai** [comment]
Yeah, I didn't. But I think it's not the same? Or else I'm missing something.  
Well whatever. The problem is solved. You can add simple note in the tutorial in the msbuild section that on arch-based distros you can encounter this problem and provide the solution I posted.

**Comment by arp242** [comment]
Actually, I just remembered someone reported a similar issue in the Reddit thread a few months ago; seems to be the same thing: https://old.reddit.com/r/RimWorld/comments/pxomto/getting_started_with_rimworld_modding_on_linux/hgq29xu/ – looks like you got your script to fix it from the same linked CKAN page as well.

I'll add a note about it, although it seems a really ugly solution to me.
